--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dorian/wallpapers/walls/wallhaven-xlx51z.jpg"

-- Special
background="#0a0c0c"
foreground="#c1c2c2"
cursor="#c1c2c2"

-- Colors
color0="#0a0c0c"
color1="#302e33"
color2="#2c333f"
color3="#2c374b"
color4="#39393c"
color5="#4b423f"
color6="#3d404a"
color7="#8a9696"
color8="#566969"
color9="#413E44"
color10="#3B4455"
color11="#3B4A65"
color12="#4D4C51"
color13="#645954"
color14="#525663"
color15="#c1c2c2"
