# Shell variables
# Generated by 'wal'
wallpaper="/home/dorian/wallpapers/walls/wallhaven-xlx51z.jpg"

# Special
background='#0a0c0c'
foreground='#c1c2c2'
cursor='#c1c2c2'

# Colors
color0='#0a0c0c'
color1='#302e33'
color2='#2c333f'
color3='#2c374b'
color4='#39393c'
color5='#4b423f'
color6='#3d404a'
color7='#8a9696'
color8='#566969'
color9='#413E44'
color10='#3B4455'
color11='#3B4A65'
color12='#4D4C51'
color13='#645954'
color14='#525663'
color15='#c1c2c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
